apiVersion: v1
kind: Pod
metadata:
  name: volume-share-devops
  namespace: default
spec:
  containers:
  - name: volume-container-devops-1
    image: ubuntu:latest
    command:
    - sleep
    - "3600"
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/blog
  - name: volume-container-devops-2
    image: ubuntu:latest
    command:
    - sleep
    - "3600"
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/apps
  volumes:
  - name: volume-share
    emptyDir:
      sizeLimit: 500Mi